import type { Field, FieldUpdate, User } from "@/types/models";

export const users: User[] = [
  {
    id: "u-admin",
    username: "admin.mavuno",
    email: "admin@mavuno.local",
    fullName: "Mavuno Admin",
    role: "admin",
    assignedFieldIds: ["f-001", "f-002", "f-003"],
    dateJoined: "2026-01-10T08:00:00.000Z",
  },
  {
    id: "u-agent-1",
    username: "agent.anne",
    email: "anne@mavuno.local",
    fullName: "Anne Mwangi",
    role: "agent",
    assignedFieldIds: ["f-001", "f-004"],
    dateJoined: "2026-02-01T08:00:00.000Z",
  },
  {
    id: "u-agent-2",
    username: "agent.juma",
    email: "juma@mavuno.local",
    fullName: "Juma Otieno",
    role: "agent",
    assignedFieldIds: ["f-002", "f-003"],
    dateJoined: "2026-02-02T08:00:00.000Z",
  },
];

export const fields: Field[] = [
  {
    id: "f-001",
    name: "North Plot",
    cropType: "Maize",
    plantingDate: "2026-02-10",
    currentStage: "vegetative",
    status: "active",
    assignedAgentId: "u-agent-1",
    notes: "Healthy growth and stable moisture.",
    createdAt: "2026-02-10T09:00:00.000Z",
    sizeHectares: 2.1,
    locationLabel: "Sector A",
  },
  {
    id: "f-002",
    name: "River Bend",
    cropType: "Beans",
    plantingDate: "2026-02-01",
    currentStage: "flowering",
    status: "active",
    assignedAgentId: "u-agent-2",
    notes: "Early flowering; monitor leaf color.",
    createdAt: "2026-02-01T09:00:00.000Z",
    sizeHectares: 1.4,
    locationLabel: "Sector B",
  },
  {
    id: "f-003",
    name: "South Terrace",
    cropType: "Tomatoes",
    plantingDate: "2026-01-26",
    currentStage: "fruiting",
    status: "at-risk",
    assignedAgentId: "u-agent-2",
    notes: "Mild pest pressure at perimeter.",
    createdAt: "2026-01-26T09:00:00.000Z",
    sizeHectares: 1.1,
    locationLabel: "Sector C",
  },
  {
    id: "f-004",
    name: "East Ridge",
    cropType: "Sunflower",
    plantingDate: "2026-02-20",
    currentStage: "germination",
    status: "active",
    assignedAgentId: "u-agent-1",
    notes: "Uniform emergence after first rain.",
    createdAt: "2026-02-20T09:00:00.000Z",
    sizeHectares: 2.7,
    locationLabel: "Sector D",
  },
];

export const fieldUpdates: FieldUpdate[] = [
  {
    id: "fu-001",
    fieldId: "f-001",
    stage: "germination",
    notes: "Seedlings emerged across 90% of rows.",
    agentId: "u-agent-1",
    timestamp: "2026-02-14T10:20:00.000Z",
  },
  {
    id: "fu-002",
    fieldId: "f-001",
    stage: "vegetative",
    notes: "Leaf expansion visible and consistent.",
    agentId: "u-agent-1",
    timestamp: "2026-03-01T11:10:00.000Z",
  },
  {
    id: "fu-003",
    fieldId: "f-002",
    stage: "flowering",
    notes: "Flowering now visible in central rows.",
    agentId: "u-agent-2",
    timestamp: "2026-03-02T09:05:00.000Z",
  },
  {
    id: "fu-004",
    fieldId: "f-003",
    stage: "fruiting",
    notes: "Fruit set started; early pest spots noted.",
    agentId: "u-agent-2",
    timestamp: "2026-03-03T14:40:00.000Z",
  },
  {
    id: "fu-005",
    fieldId: "f-004",
    stage: "germination",
    notes: "Steady emergence after irrigation pass.",
    agentId: "u-agent-1",
    timestamp: "2026-03-04T08:35:00.000Z",
  },
];
